local L = Scorpio("ShadowDancer")._Locale("ruRU")
if not L then return end
--Перевод ZamestoTV
L["NONE"] = "Без привязки"
L["MAIN"] = "Основная панель действий"
L["BAR1"] = "Панель действий 1"
L["BAR2"] = "Панель действий 2"
L["BAR3"] = "Панель действий 3"
L["BAR4"] = "Панель действий 4"
L["BAR5"] = "Панель действий 5"
L["BAR6"] = "Панель действий 6"
L["PET"] = "Панель действий питомца"
L["STANCEBAR"] = "Панель стоек"

L["popupduration"] = "Время отображения всплывающей панели"
L["flyoutconfirmtime"] = "Время подтверждения создания всплывающей панели"
L["usekeydown"] = "Применение при нажатии кнопки"
L["lockbar"] = "Заблокировать панель действий"
L["hidemainmenubar"] = "Скрыть основную панель действий"
L["hidestancebar"] = "Скрыть панель стоек"
L["hidemicrobuttonandbagsbar"] = "Скрыть панель сумок"
L["hidepetactionbar"] = "Скрыть панель питомца"
L["hidestatustrackingbarmanager"] = "Скрыть полосу опыта"
L["hideplayercastingbarframe"] = "Скрыть полосу заклинаний"
L["hidemicromenu"] = "Скрыть микроменю"
L["activemasqueskin"] = "Скин Masque"

L["RaidTarget"] = "Метки рейда"
L["WorldMarker"] = "Мировые метки"
L["BagSlot"] = "Сумки"
L["EquipSet"] = "Комплекты экипировки"
L["Item"] = "Предметы из сумок"

L["Unlock the action bars"] = "Разблокировать панели действий"
L["Lock the action bars"] = "Заблокировать панели действий"
L["Start binding key"] = "Начать привязку клавиш"
L["Start binding auto gen rule"] = "Начать привязку правил автогенерации"
L["Start binding custom name and texture"] = "Начать настройку пользовательских имен и текстур кнопок"

L["Custom Action"] = "Пользовательское действие"
L["Button Operation"] = "Специальная привязка кнопок"
L["Custom Name & Icon Bind"] = "Привязка пользовательских имен и значков"
L["Custom Name"] = "Пользовательское имя"
L["Macro Text"] = "Текст макроса"
L["Cancel"] = "Отмена"
L["Next Page"] = "Следующая страница"
L["Prev Page"] = "Предыдущая страница"

L["Lock Bar"] = "Закрыть меню"
L["Add Bar"] = "Добавить панель действий"
L["Do you want create a new action bar?"] = "Создать новую панель действий?"
L["Start Key Binding"] = "Начать привязку клавиш"
L["Global Settings"] = "Глобальные настройки"
L["Flyout Popup Duration"] = "Время отображения всплывающей панели"
L["Choose the flyout popup duration"] = "Выберите время отображения всплывающей панели"
L["Lock Action"] = "Заблокировать содержимое кнопок"
L["Use Mouse Down"] = "Срабатывание по нажатию мыши"
L["Hide original action bar"] = "Скрыть оригинальную панель действий"
L["Action Bar Settings"] = "Настройки панели действий"
L["Global Bar"] = "Общая для всех персонажей"
L["Action Bar Map"] = "Привязка панели действий"
L["Column Count"] = "Количество столбцов"
L["Choose the column count"] = "Выберите количество столбцов"
L["Row Count"] = "Количество строк"
L["Choose the row count"] = "Выберите количество строк"
L["Scale"] = "Масштаб"
L["Choose the scale"] = "Выберите масштаб"
L["Horizontal Spacing"] = "Горизонтальный интервал"
L["Choose the horizontal spacing"] = "Выберите горизонтальный интервал"
L["Vertical Spacing"] = "Вертикальный интервал"
L["Choose the vertical spacing"] = "Выберите вертикальный интервал"
L["Always Show Grid"] = "Показывать пустые кнопки"
L["Auto Fade"] = "Автозатухание"
L["Fade Alpha"] = "Прозрачность автозатухания"
L["Choose the final fade alpha"] = "Выберите конечную прозрачность"
L["Auto Hide"] = "Автоскрытие"
L["Delete Bar"] = "Удалить панель действий"
L["Do you want delete the action bar?"] = "Удалить эту панель действий?"
L["Add Macro Condition"] = "Добавить условие макроса"
L["Please select the macro condition"] = "Выберите условие автоскрытия макроса"
L["Do you want delete the macro condition"] = "Удалить это условие макроса?"

L["Masque Skin"] = "Скин Masque"

L["Auto Gen Black List"] = "Чёрный список автогенерации"
L["Auto Gen"] = "Автогенерация"
L["Start Binding"] = "Начать привязку"
L["Black List"] = "Чёрный список предметов"

L["Import/Export"] = "Импорт/Экспорт"
L["Export"] = "Экспорт"
L["Import"] = "Импорт"
L["Export Current Bar"] = "Экспортировать текущую панель действий"
L["Next"] = "Далее"
L["Close"] = "Закрыть"
L["Global Action Bars"] = "Общие панели действий для всех персонажей"
L["Current Action Bars"] = "Текущие панели действий"
L["Clear Existed Bars"] = "Удалить существующие панели действий"

L["Auto Gen Type"] = "Тип автогенерации"
L["Item Class"] = "Тип предмета"
L["Item Sub Class"] = "Подтип предмета"
L["Confirm"] = "Подтвердить"
L["All"] = "Все"
L["NONE"] = "Без автогенерации"
L["Auto Gen Binding"] = "Настройки автогенерации"

L["Show Style Border"] = "Показывать особую рамку"
L["Disable Auto Flyout"] = "Отключить автопоявление при наведении"

L["Start Swap Mode Binding"] = "Начать привязку режима обмена действиями"
L["Change the swap mode of the flyout bar"] = "Изменить режим обмена действиями всплывающей панели"
L["No action swap"] = "Запретить обмен действиями"
L["Swap the action to root button"] = "Обменять действие с корневой кнопкой при клике"
L["Use the bar as the action queue"] = "Использовать всплывающую панель как очередь заклинаний"
L["Cast to toggle flyout"] = "Переключать всплывающую панель"
