local L                         = Scorpio("ShadowDancer")._Locale("zhCN")
if not L then return end

L["NONE"]                       = "无映射"
L["MAIN"]                       = "主动作条"
L["BAR1"]                       = "动作条1"
L["BAR2"]                       = "动作条2"
L["BAR3"]                       = "动作条3"
L["BAR4"]                       = "动作条4"
L["BAR5"]                       = "动作条5"
L["BAR6"]                       = "动作条6"
L["PET"]                        = "宠物动作条"

L["Lock Bar"] 					= "关闭菜单"
L["Add Bar"]                    = "添加动作条"
L["Do you want create a new action bar?"] = "是否创建新的动作条?"
L["Start Key Binding"]          = "开始按键绑定"
L["Global Settings"]            = "全局设定"
L["Flyout Popup Duration"]      = "弹出条显示时间"
L["Choose the flyout popup duration"] = "选择弹出条的显示时间"
L["Lock Action"]                = "锁定按钮内容"
L["Use Mouse Down"]             = "按下鼠标触发"
L["Hide original action bar"]   = "隐藏原始动作条"
L["Action Bar Settings"]        = "动作条设定"
L["Global Bar"]                 = "全账号通用"
L["Action Bar Map"]             = "动作条映射"
L["Column Count"]               = "列数"
L["Choose the column count"]    = "选择列数"
L["Row Count"]                  = "行数"
L["Choose the row count"]       = "选择行数"
L["Scale"]                      = "缩放"
L["Choose the scale"]           = "选择缩放"
L["Horizontal Spacing"]         = "水平间距"
L["Choose the horizontal spacing"] = "选择水平间距"
L["Vertical Spacing"]           = "垂直间距"
L["Choose the vertical spacing"]= "选择垂直间距"
L["Always Show Grid"]           = "显示空按钮"
L["Auto Fade"]                  = "自动渐隐"
L["Fade Alpha"]                 = "自动渐隐透明度"
L["Choose the final fade alpha"]= "选择最终透明度"
L["Auto Hide"]                  = "自动隐藏"
L["Delete Bar"]                 = "删除动作条"
L["Do you want delete the action bar?"] = "是否删除该动作条?"
L["Add Macro Condition"]        = "添加宏条件"
L["Please select the macro condition"] = "请选择自动隐藏的宏条件"
L["Do you want delete the macro condition"] = "你是否要删除该宏条件?"

L["Masque Skin"]          		= "Masque皮肤"