local L                         = Scorpio("ShadowDancer")._Locale("zhCN")
if not L then return end

L["NONE"]                       = "无映射"
L["MAIN"]                       = "主动作条"
L["BAR1"]                       = "动作条1"
L["BAR2"]                       = "动作条2"
L["BAR3"]                       = "动作条3"
L["BAR4"]                       = "动作条4"
L["BAR5"]                       = "动作条5"
L["BAR6"]                       = "动作条6"
L["PET"]                        = "宠物动作条"
L["STANCEBAR"]                  = "姿态条"


L["popupduration"] 				= "弹出条显示时间"
L["flyoutconfirmtime"] 			= "创建弹出条的确认时间"
L["usekeydown"] 				= "按下按钮施法"
L["lockbar"] 					= "锁定动作条"
L["hidemainmenubar"] 			= "隐藏主动作条"
L["hidestancebar"] 				= "隐藏姿态栏"
L["hidemicrobuttonandbagsbar"] 	= "隐藏背包栏"
L["hidepetactionbar"] 			= "隐藏宠物栏"
L["hidestatustrackingbarmanager"] = "隐藏经验条"


L["RaidTarget"]                 = "团队标记"
L["WorldMarker"]                = "世界标记"
L["BagSlot"]                    = "背包"
L["EquipSet"]                   = "套装"
L["Item"]                       = "背包物品"

L["Unlock the action bars"]     = "解锁动作条"
L["Lock the action bars"]       = "锁定动作条"
L["Start binding key"]          = "开始绑定按键"
L["Start binding auto gen rule"]= "开始自动生成规则绑定"
L["Start binding custom name and texture"] = "开始设置自定义按钮名字和材质"

L["Custom Action"]              = "自定义动作"
L["Button Operation"]           = "按钮特殊绑定"
L["Custom Name & Icon Bind"]    = "自定义名字和图标绑定"
L["Custom Name"]                = "自定义名字"
L["Macro Text"]                 = "宏文本"
L["Cancel"]                     = "取消"
L["Next Page"]                  = "下一页"
L["Prev Page"]                  = "上一页"

L["Lock Bar"]                   = "关闭菜单"
L["Add Bar"]                    = "添加动作条"
L["Do you want create a new action bar?"] = "是否创建新的动作条?"
L["Start Key Binding"]          = "开始按键绑定"
L["Global Settings"]            = "全局设定"
L["Flyout Popup Duration"]      = "弹出条显示时间"
L["Choose the flyout popup duration"] = "选择弹出条的显示时间"
L["Lock Action"]                = "锁定按钮内容"
L["Use Mouse Down"]             = "按下鼠标触发"
L["Hide original action bar"]   = "隐藏原始动作条"
L["Action Bar Settings"]        = "动作条设定"
L["Global Bar"]                 = "全账号通用"
L["Action Bar Map"]             = "动作条映射"
L["Column Count"]               = "列数"
L["Choose the column count"]    = "选择列数"
L["Row Count"]                  = "行数"
L["Choose the row count"]       = "选择行数"
L["Scale"]                      = "缩放"
L["Choose the scale"]           = "选择缩放"
L["Horizontal Spacing"]         = "水平间距"
L["Choose the horizontal spacing"] = "选择水平间距"
L["Vertical Spacing"]           = "垂直间距"
L["Choose the vertical spacing"]= "选择垂直间距"
L["Always Show Grid"]           = "显示空按钮"
L["Auto Fade"]                  = "自动渐隐"
L["Fade Alpha"]                 = "自动渐隐透明度"
L["Choose the final fade alpha"]= "选择最终透明度"
L["Auto Hide"]                  = "自动隐藏"
L["Delete Bar"]                 = "删除动作条"
L["Do you want delete the action bar?"] = "是否删除该动作条?"
L["Add Macro Condition"]        = "添加宏条件"
L["Please select the macro condition"] = "请选择自动隐藏的宏条件"
L["Do you want delete the macro condition"] = "你是否要删除该宏条件?"

L["Masque Skin"]                = "Masque皮肤"

L["Auto Gen Black List"]        = "自动生成物品黑名单"
L["Auto Gen"]                   = "自动生成"
L["Start Binding"]              = "开始绑定"
L["Black List"]                 = "物品黑名单"

L["Import/Export"]              = "导入/导出"
L["Export"]                     = "导出"
L["Import"]                     = "导入"
L["Export Current Bar"]         = "导出当前动作条"
L["Next"]                       = "下一步"
L["Close"]                      = "关闭"
L["Global Action Bars"]         = "全角色通用动作条"
L["Current Action Bars"]        = "当前动作条"
L["Clear Existed Bars"]         = "移除现有动作条"

L["Auto Gen Type"]              = "自动生成类型"
L["Item Class"]                 = "物品类型"
L["Item Sub Class"]             = "物品子类型"
L["Confirm"]                    = "确定"
L["All"]                        = "全部"
L["NONE"]                       = "无自动生成"
L["Auto Gen Binding"]           = "自动生成设定"

L["Show Style Border"]          = "显示特殊边框"
L["Disable Auto Flyout"]        = "禁用鼠标划过自动弹出"

L["Start Swap Mode Binding"]    = "开始动作交换模式绑定"
L["Change the swap mode of the flyout bar"] = "修改弹出条的动作交换模式"
L["No action swap"]                         = "禁止动作交换"
L["Swap the action to root button"]         = "点击按钮动作和根按钮交换"
L["Use the bar as the action queue"]        = "弹出条做为施法队列"