local L                         = Scorpio("ShadowDancer")._Locale("zhTW")
if not L then return end

L["NONE"]                       = "無映射"
L["MAIN"]                       = "主動作條"
L["BAR1"]                       = "動作條1"
L["BAR2"]                       = "動作條2"
L["BAR3"]                       = "動作條3"
L["BAR4"]                       = "動作條4"
L["BAR5"]                       = "動作條5"
L["BAR6"]                       = "動作條6"
L["PET"]                        = "寵物動作條"
L["STANCEBAR"]                  = "姿態條"


L["popupduration"] 				= "彈出條顯示時間"
L["flyoutconfirmtime"] 			= "創建彈出條的確認時間"
L["usekeydown"] 				= "按下按鈕施法"
L["lockbar"] 					= "鎖定動作條"
L["hidemainmenubar"] 			= "隱藏主動作條"
L["hidestancebar"] 				= "隱藏姿態欄"
L["hidemicrobuttonandbagsbar"] 	= "隱藏背包欄"
L["hidepetactionbar"] 			= "隱藏寵物欄"
L["hidestatustrackingbarmanager"] = "隱藏經驗條"
L["hideplayercastingbarframe"] 	= "隱藏施法條"
L["hidemicromenu"] 				= "隱藏微型菜單"


L["RaidTarget"]                 = "團隊標記"
L["WorldMarker"]                = "世界標記"
L["BagSlot"]                    = "背包"
L["EquipSet"]                   = "套裝"
L["Item"]                       = "背包物品"

L["Unlock the action bars"]     = "解鎖動作條"
L["Lock the action bars"]       = "鎖定動作條"
L["Start binding key"]          = "開始綁定按鍵"
L["Start binding auto gen rule"]= "開始自動生成規則綁定"
L["Start binding custom name and texture"] = "開始設置自定義按鈕名字和材質"

L["Custom Action"]              = "自定義動作"
L["Button Operation"]           = "按鈕特殊綁定"
L["Custom Name & Icon Bind"]    = "自定義名字和圖標綁定"
L["Custom Name"]                = "自定義名字"
L["Macro Text"]                 = "宏文本"
L["Cancel"]                     = "取消"
L["Next Page"]                  = "下一頁"
L["Prev Page"]                  = "上一頁"

L["Lock Bar"]                   = "關閉菜單"
L["Add Bar"]                    = "添加動作條"
L["Do you want create a new action bar?"] = "是否創建新的動作條?"
L["Start Key Binding"]          = "開始按鍵綁定"
L["Global Settings"]            = "全局設定"
L["Flyout Popup Duration"]      = "彈出條顯示時間"
L["Choose the flyout popup duration"] = "選擇彈出條的顯示時間"
L["Lock Action"]                = "鎖定按鈕內容"
L["Use Mouse Down"]             = "按下鼠標觸發"
L["Hide original action bar"]   = "隱藏原始動作條"
L["Action Bar Settings"]        = "動作條設定"
L["Global Bar"]                 = "全賬號通用"
L["Action Bar Map"]             = "動作條映射"
L["Column Count"]               = "列數"
L["Choose the column count"]    = "選擇列數"
L["Row Count"]                  = "行數"
L["Choose the row count"]       = "選擇行數"
L["Scale"]                      = "縮放"
L["Choose the scale"]           = "選擇縮放"
L["Horizontal Spacing"]         = "水平間距"
L["Choose the horizontal spacing"] = "選擇水平間距"
L["Vertical Spacing"]           = "垂直間距"
L["Choose the vertical spacing"]= "選擇垂直間距"
L["Always Show Grid"]           = "顯示空按鈕"
L["Auto Fade"]                  = "自動漸隱"
L["Fade Alpha"]                 = "自動漸隱透明度"
L["Choose the final fade alpha"]= "選擇最終透明度"
L["Auto Hide"]                  = "自動隱藏"
L["Delete Bar"]                 = "刪除動作條"
L["Do you want delete the action bar?"] = "是否刪除該動作條?"
L["Add Macro Condition"]        = "添加宏條件"
L["Please select the macro condition"] = "請選擇自動隱藏的宏條件"
L["Do you want delete the macro condition"] = "你是否要刪除該宏條件?"

L["Masque Skin"]                = "Masque皮膚"

L["Auto Gen Black List"]        = "自動生成物品黑名單"
L["Auto Gen"]                   = "自動生成"
L["Start Binding"]              = "開始綁定"
L["Black List"]                 = "物品黑名單"

L["Import/Export"]              = "導入/導出"
L["Export"]                     = "導出"
L["Import"]                     = "導入"
L["Export Current Bar"]         = "導出當前動作條"
L["Next"]                       = "下一步"
L["Close"]                      = "關閉"
L["Global Action Bars"]         = "全角色通用動作條"
L["Current Action Bars"]        = "當前動作條"
L["Clear Existed Bars"]         = "移除現有動作條"

L["Auto Gen Type"]              = "自動生成類型"
L["Item Class"]                 = "物品類型"
L["Item Sub Class"]             = "物品子類型"
L["Confirm"]                    = "確定"
L["All"]                        = "全部"
L["NONE"]                       = "無自動生成"
L["Auto Gen Binding"]           = "自動生成設定"

L["Show Style Border"]          = "顯示特殊邊框"
L["Disable Auto Flyout"]        = "禁用鼠標劃過自動彈出"

L["Start Swap Mode Binding"]    = "開始動作交換模式綁定"
L["Change the swap mode of the flyout bar"] = "修改彈出條的動作交換模式"
L["No action swap"]                         = "禁止動作交換"
L["Swap the action to root button"]         = "點擊按鈕動作和根按鈕交換"
L["Use the bar as the action queue"]        = "彈出條做為施法隊列"
L["Cast to toggle flyout"] 	 	= "切換彈出條"